branch-defaults:
  master:
    environment: nameMyProjects-env
global:
  application_name: My First Elastic Beanstalk Application
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.09 v2.0.6 running Python 3.4
  default_region: us-west-2
  profile: null
  sc: git
